- hosts: all
  become: yes
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install prerequisites for Docker repository
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - gpg
          - lsb-release
        state: present
      register: prereq_installation

    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      depends: prereq_installation

    - name: add Docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      depends: prereq_installation
      
    - name: add Docker's APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: 'docker'

    - name: install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Run whoami without become
      command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: Set a fact with the user name
      set_fact:
        login_user: '{{ whoami.stdout }}'

    - name: Add the current user to 'docker' group
      become: yes
      user:
        name: '{{ whoami.stdout }}'
        groups: docker
        append: yes

    - name: Reset SSH connection to refresh user groups
      meta: reset_connection
